### PR TITLE
workdir

### LINKED ISSUE #52: Option to change workdir
One may wants to checkout the cache outside of drones shared working directory.

This could be solved by changing the working directory during the start of the plugin.

### PR DESCRIPTION
**Pull request by foosinn**
Adds an option to change the working directory.

This allows to extract the cache outside of the source directory.

closes #52

### CODE REVIEW

**Comment by tboerger** [comment]
IMHO a workdir doesn't make sense. Instead of that we should fix the plugin to accept absolute paths, and not only paths within the working directory.

**Comment by foosinn** [comment]
You can supply any absolute path you want. I use it for `/cache`.

I called it *workdir* since it simply changes the working directory of the cache plugin before running the plugin.

**Comment by tboerger** [comment]
Absolute paths are not working currently. they are getting cached, but they are getting restored into the wrong path so far.

**Comment by foosinn** [comment]
Sorry i didn't understand your first reply correctly.

I guess changing the behavior is a lot cleaner, but will break existing cache directories, since tar files contain only relative paths.

An boolean option like `PLUGIN_ABSOLUTE` is an option, but leads to the same behavior as `PLUGIN_WORKDIR=/`. 

Any ideas how to solve this without breaking existing changes?

**Comment by tboerger** [comment]
We got to introduce a breaking change anyway, but I'm not sure if we should introduce it because of some working directory...

**Comment by bradrydzewski** [comment]
what is the purpose of the `path` parameter?  I feel like `path` should solve this problem since it is joined with the filenames.

**Comment by foosinn** [comment]
AFAIK tar files have a directory structure but no information if the path is absolute or not. That's why packaging with relative and absolute paths both works but unpacking amuses paths relative to the working directory.

**Review by techknowlogick — COMMENTED** [review]
Thanks for PR :)

This contains unrelated changes, such as a symlink for `Dockerfile`, new empty lines, go.mod changes and case changes. Could you remove those so it is just the changes that need to be reviewed as part of this PR?

**Comment by donny-dont** [comment]
@techknowlogick we're not sure about this change at this time. Feels like it should be in the cache lib TBH.

**Comment by foosinn** [comment]
sorry, just did changes for our fork!

**Comment by donny-dont** [comment]
@foosinn I'm not against the patch it just seems like it should live at https://github.com/drone/drone-cache-lib

**Pull request closed without merging**
