### PR TITLE
Updated to current build process

### PR DESCRIPTION
**Pull request by tboerger**

### CODE REVIEW

**Comment by tonglil** [comment]
What can we do to get the build to pass? It's breaking on a `minio` dependency.

**Comment by donny-dont** [comment]
@tboerger I think we should print out `dep status` before exiting in the `deps` step so one can verify things are correct.

**Comment by donny-dont** [comment]
@tonglil @tboerger I think this will make the build happy on appveyor now.

**Comment by tboerger** [comment]
> @tboerger I think we should print out dep status before exiting in the deps step so one can verify things are correct.

Maybe you want to do that for the other plugins as well? 8)

**Comment by tboerger** [comment]
But anyway, thanks for fixing my PR.

**Pull request merged**
