### PR TITLE
Allow default credential chain to be used

### PR DESCRIPTION
**Pull request by AKoetsier**
I also had to update the vendored minio to use the default credential chain.

### CODE REVIEW

**Comment by AKoetsier** [comment]
Looks like the build started before the pr was available? Can somebody restart the build?

**Comment by appleboy** [comment]
@AKoetsier restarted. You can push commit again to restart the build.

**Comment by AKoetsier** [comment]
@appleboy tnx!

**Comment by tboerger** [comment]
Sorry I missed that you upgraded Minio... I have done that in another pr, can you update this pr please?

**Comment by AKoetsier** [comment]
Done

**Pull request merged**
